-- CutisPathLab tables
IF OBJECT_ID('dbo.Test', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Test (
    id NVARCHAR(50) NOT NULL PRIMARY KEY,
    code NVARCHAR(50) NOT NULL UNIQUE,
    name NVARCHAR(255) NOT NULL,
    category NVARCHAR(100) NOT NULL,
    price FLOAT NOT NULL,
    originalPrice FLOAT NULL,
    description NVARCHAR(MAX) NULL,
    sampleType NVARCHAR(50) NULL,
    fastingRequired BIT NOT NULL CONSTRAINT DF_Test_fasting DEFAULT 0,
    reportTime NVARCHAR(50) NULL,
    parameters INT NULL,
    popular BIT NOT NULL CONSTRAINT DF_Test_popular DEFAULT 0,
  iconUrl NVARCHAR(500) NULL,
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_Test_created DEFAULT SYSUTCDATETIME(),
    updatedAt DATETIME2 NOT NULL CONSTRAINT DF_Test_updated DEFAULT SYSUTCDATETIME()
  );
END;
GO

IF OBJECT_ID('dbo.Booking', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.Booking (
    id NVARCHAR(50) NOT NULL PRIMARY KEY,
    name NVARCHAR(150) NOT NULL,
    phone NVARCHAR(30) NOT NULL,
    email NVARCHAR(150) NULL,
    address NVARCHAR(500) NULL,
    preferredDate NVARCHAR(50) NULL,
    preferredTime NVARCHAR(50) NULL,
    notes NVARCHAR(MAX) NULL,
    status NVARCHAR(30) NOT NULL CONSTRAINT DF_Booking_status DEFAULT 'pending',
    testId NVARCHAR(50) NULL,
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_Booking_created DEFAULT SYSUTCDATETIME(),
    updatedAt DATETIME2 NOT NULL CONSTRAINT DF_Booking_updated DEFAULT SYSUTCDATETIME(),
    CONSTRAINT FK_Booking_Test FOREIGN KEY (testId) REFERENCES dbo.Test(id)
  );
END;
GO

IF OBJECT_ID('dbo.ContactMessage', 'U') IS NULL
BEGIN
  CREATE TABLE dbo.ContactMessage (
    id NVARCHAR(50) NOT NULL PRIMARY KEY,
    name NVARCHAR(150) NOT NULL,
    email NVARCHAR(150) NOT NULL,
    phone NVARCHAR(30) NULL,
    subject NVARCHAR(255) NULL,
    message NVARCHAR(MAX) NOT NULL,
    createdAt DATETIME2 NOT NULL CONSTRAINT DF_Contact_created DEFAULT SYSUTCDATETIME()
  );
END;
GO

SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = 'dbo'
ORDER BY TABLE_NAME;
GO
